version: "3.8"
networks:
  localstack-net:
    name: localstack-net
    driver: bridge
 
services:
  localstack:
    image: localstack/localstack
    privileged: true
    networks:
      - localstack-net
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=sqs
    volumes:
      - ./.temp/localstack:/tmp/localstack