AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  BCS: Butter Chicken Supper

Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: True
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: true

Resources:
  ChickenApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      
  GetMenuFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-menu/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Returns the menu for BCS.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
          IS_OFFLINE: ""
      Events:
        Api:
          Type: Api
          Properties:
            Path: /menu
            Method: GET
            RestApiId: !Ref ChickenApi
        Options:
          Type: Api
          Properties:
            RestApiId: !Ref ChickenApi
            Path: /menu
            Method: options
            Auth:
              ApiKeyRequired: false

  SubmitOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/submit-order/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          SAMPLE_TABLE: !Ref SampleTable
          IS_OFFLINE: ""
      Events:
        Api:
          Type: Api
          Properties:
            Path: /order
            Method: POST
            RestApiId: !Ref ChickenApi
        Options:
          Type: Api
          Properties:
            RestApiId: !Ref ChickenApi
            Path: /order
            Method: options
            Auth:
              ApiKeyRequired: false

  SampleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SampleTable
      AttributeDefinitions:
          # Index attributes
          - AttributeName: partitionKey
            AttributeType: S
          - AttributeName: sortKey
            AttributeType: S
      KeySchema:
          - AttributeName: partitionKey
            KeyType: HASH
          - AttributeName: sortKey
            KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  SubmitOrderArn:
    Description: "Stock Trading state machine ARN"
    Value: !Ref SubmitOrderFunction
  SubmitOrderRole:
    Description: "IAM Role created based on the specified SAM Policy Templates"
    Value: !GetAtt SubmitOrderFunction.Arn
